// Code generated by tools/generate_registry.go. DO NOT EDIT.
package main


import (
	"time"
	"janisvepris/aoc/internal/crap"

	day01_2022 "janisvepris/aoc/2022/day01"
	day02_2022 "janisvepris/aoc/2022/day02"
	day03_2022 "janisvepris/aoc/2022/day03"
	day04_2022 "janisvepris/aoc/2022/day04"
	day05_2022 "janisvepris/aoc/2022/day05"
	day06_2022 "janisvepris/aoc/2022/day06"
	day07_2022 "janisvepris/aoc/2022/day07"
	day08_2022 "janisvepris/aoc/2022/day08"
	day09_2022 "janisvepris/aoc/2022/day09"
	day10_2022 "janisvepris/aoc/2022/day10"
	day11_2022 "janisvepris/aoc/2022/day11"
	day12_2022 "janisvepris/aoc/2022/day12"
	day01_2023 "janisvepris/aoc/2023/day01"
	day02_2023 "janisvepris/aoc/2023/day02"
	day03_2023 "janisvepris/aoc/2023/day03"
	day04_2023 "janisvepris/aoc/2023/day04"
	day05_2023 "janisvepris/aoc/2023/day05"
	day06_2023 "janisvepris/aoc/2023/day06"
	day07_2023 "janisvepris/aoc/2023/day07"
	day08_2023 "janisvepris/aoc/2023/day08"
	day09_2023 "janisvepris/aoc/2023/day09"
	day10_2023 "janisvepris/aoc/2023/day10"
	day11_2023 "janisvepris/aoc/2023/day11"
	day12_2023 "janisvepris/aoc/2023/day12"
	day13_2023 "janisvepris/aoc/2023/day13"
	day14_2023 "janisvepris/aoc/2023/day14"
	day15_2023 "janisvepris/aoc/2023/day15"
	day16_2023 "janisvepris/aoc/2023/day16"
	day01_2024 "janisvepris/aoc/2024/day01"
	day02_2024 "janisvepris/aoc/2024/day02"
	day03_2024 "janisvepris/aoc/2024/day03"
	day04_2024 "janisvepris/aoc/2024/day04"
	day05_2024 "janisvepris/aoc/2024/day05"
	day06_2024 "janisvepris/aoc/2024/day06"
	day07_2024 "janisvepris/aoc/2024/day07"
	day08_2024 "janisvepris/aoc/2024/day08"
	day01_2025 "janisvepris/aoc/2025/day01"
	day02_2025 "janisvepris/aoc/2025/day02"
	day03_2025 "janisvepris/aoc/2025/day03"
	day04_2025 "janisvepris/aoc/2025/day04"
	day05_2025 "janisvepris/aoc/2025/day05"
	day06_2025 "janisvepris/aoc/2025/day06"
	day07_2025 "janisvepris/aoc/2025/day07"
	day08_2025 "janisvepris/aoc/2025/day08"
)


func runSolution(setup, part1, part2 func()) {
	setup()
	start := time.Now()
	part1()
	crap.PrintDuration(time.Since(start))
	start = time.Now()
	part2()
	crap.PrintDuration(time.Since(start))
}

var solutions = map[string]map[string]func(){
	"2022": {
		"01": func() { runSolution(day01_2022.Setup, day01_2022.Part1, day01_2022.Part2) },
		"02": func() { runSolution(day02_2022.Setup, day02_2022.Part1, day02_2022.Part2) },
		"03": func() { runSolution(day03_2022.Setup, day03_2022.Part1, day03_2022.Part2) },
		"04": func() { runSolution(day04_2022.Setup, day04_2022.Part1, day04_2022.Part2) },
		"05": func() { runSolution(day05_2022.Setup, day05_2022.Part1, day05_2022.Part2) },
		"06": func() { runSolution(day06_2022.Setup, day06_2022.Part1, day06_2022.Part2) },
		"07": func() { runSolution(day07_2022.Setup, day07_2022.Part1, day07_2022.Part2) },
		"08": func() { runSolution(day08_2022.Setup, day08_2022.Part1, day08_2022.Part2) },
		"09": func() { runSolution(day09_2022.Setup, day09_2022.Part1, day09_2022.Part2) },
		"10": func() { runSolution(day10_2022.Setup, day10_2022.Part1, day10_2022.Part2) },
		"11": func() { runSolution(day11_2022.Setup, day11_2022.Part1, day11_2022.Part2) },
		"12": func() { runSolution(day12_2022.Setup, day12_2022.Part1, day12_2022.Part2) },
	},
	"2023": {
		"01": func() { runSolution(day01_2023.Setup, day01_2023.Part1, day01_2023.Part2) },
		"02": func() { runSolution(day02_2023.Setup, day02_2023.Part1, day02_2023.Part2) },
		"03": func() { runSolution(day03_2023.Setup, day03_2023.Part1, day03_2023.Part2) },
		"04": func() { runSolution(day04_2023.Setup, day04_2023.Part1, day04_2023.Part2) },
		"05": func() { runSolution(day05_2023.Setup, day05_2023.Part1, day05_2023.Part2) },
		"06": func() { runSolution(day06_2023.Setup, day06_2023.Part1, day06_2023.Part2) },
		"07": func() { runSolution(day07_2023.Setup, day07_2023.Part1, day07_2023.Part2) },
		"08": func() { runSolution(day08_2023.Setup, day08_2023.Part1, day08_2023.Part2) },
		"09": func() { runSolution(day09_2023.Setup, day09_2023.Part1, day09_2023.Part2) },
		"10": func() { runSolution(day10_2023.Setup, day10_2023.Part1, day10_2023.Part2) },
		"11": func() { runSolution(day11_2023.Setup, day11_2023.Part1, day11_2023.Part2) },
		"12": func() { runSolution(day12_2023.Setup, day12_2023.Part1, day12_2023.Part2) },
		"13": func() { runSolution(day13_2023.Setup, day13_2023.Part1, day13_2023.Part2) },
		"14": func() { runSolution(day14_2023.Setup, day14_2023.Part1, day14_2023.Part2) },
		"15": func() { runSolution(day15_2023.Setup, day15_2023.Part1, day15_2023.Part2) },
		"16": func() { runSolution(day16_2023.Setup, day16_2023.Part1, day16_2023.Part2) },
	},
	"2024": {
		"01": func() { runSolution(day01_2024.Setup, day01_2024.Part1, day01_2024.Part2) },
		"02": func() { runSolution(day02_2024.Setup, day02_2024.Part1, day02_2024.Part2) },
		"03": func() { runSolution(day03_2024.Setup, day03_2024.Part1, day03_2024.Part2) },
		"04": func() { runSolution(day04_2024.Setup, day04_2024.Part1, day04_2024.Part2) },
		"05": func() { runSolution(day05_2024.Setup, day05_2024.Part1, day05_2024.Part2) },
		"06": func() { runSolution(day06_2024.Setup, day06_2024.Part1, day06_2024.Part2) },
		"07": func() { runSolution(day07_2024.Setup, day07_2024.Part1, day07_2024.Part2) },
		"08": func() { runSolution(day08_2024.Setup, day08_2024.Part1, day08_2024.Part2) },
	},
	"2025": {
		"01": func() { runSolution(day01_2025.Setup, day01_2025.Part1, day01_2025.Part2) },
		"02": func() { runSolution(day02_2025.Setup, day02_2025.Part1, day02_2025.Part2) },
		"03": func() { runSolution(day03_2025.Setup, day03_2025.Part1, day03_2025.Part2) },
		"04": func() { runSolution(day04_2025.Setup, day04_2025.Part1, day04_2025.Part2) },
		"05": func() { runSolution(day05_2025.Setup, day05_2025.Part1, day05_2025.Part2) },
		"06": func() { runSolution(day06_2025.Setup, day06_2025.Part1, day06_2025.Part2) },
		"07": func() { runSolution(day07_2025.Setup, day07_2025.Part1, day07_2025.Part2) },
		"08": func() { runSolution(day08_2025.Setup, day08_2025.Part1, day08_2025.Part2) },
	},
}

