// Code generated by tools/generate_registry.go. DO NOT EDIT.
package main


import (
	"fmt"
	"time"

	day01_2023 "janisvepris/aoc25/2023/day01"
	day02_2023 "janisvepris/aoc25/2023/day02"
	day03_2023 "janisvepris/aoc25/2023/day03"
	day04_2023 "janisvepris/aoc25/2023/day04"
	day05_2023 "janisvepris/aoc25/2023/day05"
	day06_2023 "janisvepris/aoc25/2023/day06"
	day07_2023 "janisvepris/aoc25/2023/day07"
	day08_2023 "janisvepris/aoc25/2023/day08"
	day09_2023 "janisvepris/aoc25/2023/day09"
	day10_2023 "janisvepris/aoc25/2023/day10"
	day11_2023 "janisvepris/aoc25/2023/day11"
	day12_2023 "janisvepris/aoc25/2023/day12"
	day13_2023 "janisvepris/aoc25/2023/day13"
	day14_2023 "janisvepris/aoc25/2023/day14"
	day15_2023 "janisvepris/aoc25/2023/day15"
	day16_2023 "janisvepris/aoc25/2023/day16"
	day01_2024 "janisvepris/aoc25/2024/day01"
	day02_2024 "janisvepris/aoc25/2024/day02"
	day03_2024 "janisvepris/aoc25/2024/day03"
	day04_2024 "janisvepris/aoc25/2024/day04"
	day05_2024 "janisvepris/aoc25/2024/day05"
	day06_2024 "janisvepris/aoc25/2024/day06"
	day07_2024 "janisvepris/aoc25/2024/day07"
	day08_2024 "janisvepris/aoc25/2024/day08"
)

func printTime(label string, d time.Duration) {
	us := d.Microseconds()

	minutes := us / 60000000
	us %= 60000000

	seconds := us / 1000000
	us %= 1000000

	milliseconds := us / 1000
	us %= 1000

	fmt.Printf("(in %dm %ds %dms %dµs)\n", minutes, seconds, milliseconds, us)
}

var solutions = map[string]map[string]func(){
	"2023": {
		"01": func() {
			day01_2023.Setup()
			start := time.Now()
			day01_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day01_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"02": func() {
			day02_2023.Setup()
			start := time.Now()
			day02_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day02_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"03": func() {
			day03_2023.Setup()
			start := time.Now()
			day03_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day03_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"04": func() {
			day04_2023.Setup()
			start := time.Now()
			day04_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day04_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"05": func() {
			day05_2023.Setup()
			start := time.Now()
			day05_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day05_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"06": func() {
			day06_2023.Setup()
			start := time.Now()
			day06_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day06_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"07": func() {
			day07_2023.Setup()
			start := time.Now()
			day07_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day07_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"08": func() {
			day08_2023.Setup()
			start := time.Now()
			day08_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day08_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"09": func() {
			day09_2023.Setup()
			start := time.Now()
			day09_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day09_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"10": func() {
			day10_2023.Setup()
			start := time.Now()
			day10_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day10_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"11": func() {
			day11_2023.Setup()
			start := time.Now()
			day11_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day11_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"12": func() {
			day12_2023.Setup()
			start := time.Now()
			day12_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day12_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"13": func() {
			day13_2023.Setup()
			start := time.Now()
			day13_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day13_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"14": func() {
			day14_2023.Setup()
			start := time.Now()
			day14_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day14_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"15": func() {
			day15_2023.Setup()
			start := time.Now()
			day15_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day15_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
		"16": func() {
			day16_2023.Setup()
			start := time.Now()
			day16_2023.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day16_2023.Part2()
			printTime("Part 2", time.Since(start))
		},
	},
	"2024": {
		"01": func() {
			day01_2024.Setup()
			start := time.Now()
			day01_2024.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day01_2024.Part2()
			printTime("Part 2", time.Since(start))
		},
		"02": func() {
			day02_2024.Setup()
			start := time.Now()
			day02_2024.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day02_2024.Part2()
			printTime("Part 2", time.Since(start))
		},
		"03": func() {
			day03_2024.Setup()
			start := time.Now()
			day03_2024.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day03_2024.Part2()
			printTime("Part 2", time.Since(start))
		},
		"04": func() {
			day04_2024.Setup()
			start := time.Now()
			day04_2024.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day04_2024.Part2()
			printTime("Part 2", time.Since(start))
		},
		"05": func() {
			day05_2024.Setup()
			start := time.Now()
			day05_2024.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day05_2024.Part2()
			printTime("Part 2", time.Since(start))
		},
		"06": func() {
			day06_2024.Setup()
			start := time.Now()
			day06_2024.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day06_2024.Part2()
			printTime("Part 2", time.Since(start))
		},
		"07": func() {
			day07_2024.Setup()
			start := time.Now()
			day07_2024.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day07_2024.Part2()
			printTime("Part 2", time.Since(start))
		},
		"08": func() {
			day08_2024.Setup()
			start := time.Now()
			day08_2024.Part1()
			printTime("Part 1", time.Since(start))
			start = time.Now()
			day08_2024.Part2()
			printTime("Part 2", time.Since(start))
		},
	},
}

